# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, pyqtSignal ,QObject


class Ui_inventory_wd(QObject):
    def setupUi(self, inventory_wd):
        inventory_wd.setObjectName("inventory_wd")
        inventory_wd.resize(886, 533)
        self.centralwidget = QtWidgets.QWidget(inventory_wd)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.date_inventory_cb = QtWidgets.QComboBox(self.centralwidget)
        self.date_inventory_cb.setObjectName("date_inventory_cb")
        self.horizontalLayout.addWidget(self.date_inventory_cb)
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setText("")
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        inventory_wd.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(inventory_wd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 20))
        self.menubar.setObjectName("menubar")
        inventory_wd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(inventory_wd)
        self.statusbar.setObjectName("statusbar")
        inventory_wd.setStatusBar(self.statusbar)

        self.retranslateUi(inventory_wd)
        QtCore.QMetaObject.connectSlotsByName(inventory_wd)

    def retranslateUi(self, inventory_wd):
        _translate = QtCore.QCoreApplication.translate
        inventory_wd.setWindowTitle(_translate("inventory_wd", "Inventory Analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inventory_wd = QtWidgets.QMainWindow()
    ui = Ui_inventory_wd()
    ui.setupUi(inventory_wd)
    inventory_wd.show()
    sys.exit(app.exec_())
